### ISSUE TITLE
Platform error sensor.aemet after upgrade to 2021.12.XX

### ISSUE THREAD

**Issue by inigoml** [outon/HomeAssistant-AEMET#15]
Version: 2021.12.3

Alfter upgrade, AEMET sensor does not work anymore:

![image](https://user-images.githubusercontent.com/7486708/146749512-d7e79400-53c6-4955-a697-2fd44bdb3f62.png)

This is due to this change in HA.
https://github.com/home-assistant/core/pull/58380

**Comment by outon** [comment]
Home Assistant now has native support for AEMET, so development of this component is stopped.

Home Assistant tiene ahora soporte nativo para AEMET, por lo que se detiene el desarrollo de este componente.
