### ISSUE TITLE
Velocidad del viento, valores 

### ISSUE THREAD

**Issue by dave-code-ruiz** [outon/HomeAssistant-AEMET#2]
sorry for english followers, today only spanish (please use translate google)

Buenas, outon

tengo una nueva incidencia, voy a intentar explicarte lo que me ocurre, estoy comprobando datos de temperatura exterior y humedad y siempre que los comparo con la web aemet.es van perfectos, ni un fallo, pero cuando se trata del viento me da un error , a veces me coinciden , pero lo normal es que se queden mas bajos, es algo bastante extraño, pero me pasa a menudo.

Te paso un ejemplo, estos son los datos de aemet de donde vivo

http://www.aemet.es/es/eltiempo/observacion/ultimosdatos?k=ext&l=XXXXX&w=0&datos=img&x=h24&f=vel_viento 
(cambiando las cinco X por mi estación)

Y en mi home-assistant utilizo un sensor que me da los valores:

- platform: template
  sensors:
    velocidad_viento:
      friendly_name: Velocidad del Viento
      unit_of_measurement: 'km/h'
      value_template: >
            {{ states.weather.aemet.attributes.wind_speed }}
      icon_template: 'mdi-weather-windy'

los valores del sensor coinciden con el weather.aemet de home assistant, pero ambos difieren con los datos de la web, los datos de las estacion son los mismos porque temperatura y humedad si coincide.

¿Que puede estar pasando? ¿Necesitas algún dato mas?

Gracias

**Comment by outon** [comment]
Yo prefiero www.deepl.com para las traducciones.

Ya he visto donde puede estar el problema. En algunos casos hay estaciones meteorológicas que no publican todos los datos. Entonces intento recuperar la información de la previsión horaria. Pero en la  página de la AEMET la información la sacan de la previsión diaria, aunque hay una pestaña que muestra la información por horas. 

Por ejemplo: Mi instalación de HA muestra: 2 km/h SO
![image](https://user-images.githubusercontent.com/6525261/65271494-90b7a600-db1d-11e9-98b3-e5663feb064c.png)

En la Web de la AEMET aparece: 10 Km/h NE, pero es la página de predicción 7 días
![image](https://user-images.githubusercontent.com/6525261/65271913-64e8f000-db1e-11e9-9c96-4e7dd8a88877.png)

Sin embargo en la pestaña de predicción horaria pone como viento 2 Km/h SO
![image](https://user-images.githubusercontent.com/6525261/65271666-e8eea800-db1d-11e9-9c12-b48415ca92a0.png)

Creo que lo correcto es mostrar en la posición central el tiempo actual que correspondería con la previsión horaria.
![image](https://user-images.githubusercontent.com/6525261/65271753-150a2900-db1e-11e9-834b-8d1115a1ec0f.png)

**Comment by dave-code-ruiz** [comment]
Gracias por el consejo de deepl.com , no lo conocia.

Creo que se cual es la diferencia, me estas hablando de previsión, y sin embargo , la web que yo te mando es de datos ya recogidos por la estación , no de previsión, yo pensaba que en el objeto weather los datos de abajo eran previsión y los datos que marcas en rojo eran datos ya recogidos, para mi es importante que sean datos reales y actuales y no previsión ya que quiero usarlo para recoger los toldos de la casa, también me interesarían los datos de "racha de viento".

De todos modos, en la pagina que yo te paso parece que la actualización de los datos es cada 1 hora, si fuera así sería un problema , supongo.

Gracias por tu ayuda y soporte

Un saludo

**Comment by outon** [comment]
Estaba preparando sensores con datos extraídos directamente de las estaciones meteorológicas. Pero me temo que la frecuencia de actualización es horaria por mucho que diga la AEMET que la actualización es continua.

En la página web del API de Opendata de AEMET se indica que la frecuencia de actualización es continua, sin embargo los datos son horarios según se deduce de la descripción de los datos.

![image](https://user-images.githubusercontent.com/6525261/65305240-f2f6c200-db82-11e9-9ab7-6fcad165c580.png)

En la especificación de los datos que se obtienen se indica siempre que los datos hacen referencia a los **XX minutos anteriores a la hora "fint"** y esta fecha siempre es un número redondo:

```JSON
{
	"id": "vmax",
	"descripcion": "Velocidad máxima del viento, valor máximo del viento mantenido 3 segundos y registrado en los 60 minutos anteriores a la hora indicada por el período de observación 'fint' (m/s)",
	"tipo_datos": "float",
	"requerido": false
},
{
	"id": "dmax",
	"descripcion": "Dirección del viento máximo registrado en los 60 minutos anteriores a la hora indicada por 'fint' (grados)",
	"tipo_datos": "float",
	"requerido": false
},
{
	"id": "vv",
	"descripcion": "Velocidad media del viento, media escalar de las muestras adquiridas cada 0,25 ó 1 segundo en el período de 10 minutos anterior al indicado por 'fint' (m/s)",
	"tipo_datos": "float",
	"requerido": false
},

{
	"id": "dv",
	"descripcion": "Dirección media del viento, en el período de 10 minutos anteriores a la fecha indicada por 'fint' (grados)",
	"tipo_datos": "float",
	"requerido": false
}
```

Por lo que para una automatización que dependa de las rachas de viento actuales, yo personalmente, no la usaría.

**Comment by dave-code-ruiz** [comment]
ok gracias, lo suponia

Un saludo
