### ISSUE TITLE
Datos de lluvia menos exactos

### ISSUE THREAD

**Issue by dave-code-ruiz** [outon/HomeAssistant-AEMET#3]
Soy yo de nuevo, ayer estuvo lloviendo en la localidad donde vivo y resulta que al comparar el Weather que trae el homeassistant y el Weather de AEMET parece que es mas exacto el de homeassistant, y me ha extrañado, entiendo que no es cosa del componente ya que este lo que hace es leer datos de la API de AEMET, ¿pero tu sabes algo respecto a la exactitud de los datos? se supone que AEMET lee de la estacion meteorologica que existe en mi localidad y deberia dar datos mas exactos.

![tempsnip](https://user-images.githubusercontent.com/34915602/66827631-63f58380-ef4f-11e9-8850-cb35869829c2.png)

**Comment by outon** [comment]
Hasta donde yo se, la AEMET parece que tiene estaciones automáticas donde se recuperan los datos y otros tipos de estaciones donde los elaboran posteriormente. Quizás la estación mas cercana a tí es de estas últimas.

Esta es la respuesta de la AEMET ante una consulta que planteé en abril 2019:

> En OpenData no se muestran los datos de la estación de Cuatro Vientos, ya que sólo se muestran datos de estaciones automáticas. Si el usted quiere obtener datos de esa estación puede consultar en la opción de "Mensajes de observación. Último elaborado" y consultar los partes synop (emite para las hora sinópticas principales: 06, 12, 18).

He revisado la web de OpenData y en el apartado de **Últimos mensajes de observación**. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.

Estos partes **_synop_**, **_temp_** y _**climat**_ están codificado según el estándar meteorológico [BUFR](https://en.wikipedia.org/wiki/BUFR)

Todavía no he tenido tiempo estudiar ese estándar ni a revisar si hay predicciones en esos ficheros, para completar la información que pudiera faltar.
