### ISSUE TITLE
line 300 [Condition] AttributeError

### ISSUE THREAD

**Issue by gargomoma** [outon/HomeAssistant-AEMET#5]
https://github.com/outon/HomeAssistant-AEMET/blob/16c68c34bb7b0e69823a7bbd89a60bb3dd9a6648/aemet/weather.py#L293

Hi, since yesterday I'm having the following issue.
I'm trying to get familiar with AEMET API to understand if the error is just mine or is happening to someone else.
In the meantime, here's what HA is showing me. I'll update the issue if I found out.

``Wed Nov 13 2019 18:24:35 GMT+0100 (hora estándar de Europa central)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 309, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/aemet/weather.py", line 141, in state
    return self.condition
  File "/config/custom_components/aemet/weather.py", line 300, in condition
    condition = self._aemet_forecast_current_hour.get("condition", "desconocido")
AttributeError: 'NoneType' object has no attribute 'get'``

**Comment by outon** [comment]
Ops!! Are you using the "master" branch?

I am developing the ASYNC version of this component and I may be messed up with different branches. I will review master branch to ensure that no code has being mixed between branches.

**Comment by gargomoma** [comment]
Hi, yes.
I'm using the master branch with the latest updates.
Let me know if there's anything I can do on my side to help you debug this.
Thanks!

**Comment by outon** [comment]
I found the error...

AEMET changed the way they inform "Fecha" field (date) and now instead of using only DATE with format "YYYY-MM-DD" they also include TIME so they complies with ISO8601.

Their new format is "YYYY-MM-DDTHH:MI:SS", they made changes but did not update "Version" field.

I have to fix my program.
